# Generated by Django 4.2.13 on 2024-06-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('received_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Beverage', 'Beverage'), ('Food Provision', 'Food Provision'), ('Sanitary', 'Sanitary'), ('Maintenance', 'Maintenance'), ('Service Aid', 'Service Aid'), ('Stationary', 'Stationary'), ('Sundry', 'Sundry'), ('Fresh Baazar', 'Fresh Baazar')], max_length=50)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('current_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_balance', models.IntegerField()),
                ('minimum_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('purchaser', models.CharField(max_length=255)),
                ('upload_receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('purchase_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.purchaserecord')),
            ],
        ),
        migrations.CreateModel(
            name='IssueRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.issuerecord')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
    ]
