# Generated by Django 4.2.13 on 2024-06-14 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('tin_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='voucher_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='voucher_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='issued_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='received_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Liter', 'Liter'), ('Meter', 'Meter'), ('Centimeter', 'Centimeter'), ('Square Meter', 'Square Meter'), ('Cubic Meter', 'Cubic Meter'), ('Crate', 'Crate'), ('Pack', 'Pack'), ('Box', 'Box'), ('Bag', 'Bag'), ('Dozen', 'Dozen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='purchaser',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='store.supplier'),
        ),
    ]
