# Generated by Django 4.2.13 on 2024-06-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_unit_of_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerecord',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='department',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='issuerecord',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Beverage', 'Beverage'), ('Food Provision', 'Food Provision'), ('Sanitary', 'Sanitary'), ('Maintenance', 'Maintenance'), ('Service Aid', 'Service Aid'), ('Stationary', 'Stationary'), ('Sundry', 'Sundry'), ('Fresh Baazar', 'Fresh Baazar')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
