# Generated by Django 4.2.11 on 2024-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_created_at_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
