# Generated by Django 4.2.11 on 2024-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_item_current_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerecord',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='purchaserecord',
            name='total_value',
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_balance',
            field=models.PositiveIntegerField(),
        ),
    ]
