# Generated by Django 4.2.11 on 2024-07-03 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_issuerecord_total_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerecord',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name', 'category'], name='store_subca_name_570e99_idx'),
        ),
    ]
