# Generated by Django 4.2.11 on 2024-06-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_alter_document_name_alter_employee_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
